# Generated by Django 6.0.6 on 2026-06-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Администратор'), ('client', 'Клиент'), ('employee', 'Сотрудник')], default='client', max_length=20),
        ),
    ]
